### ISSUE TITLE
Content license

### ISSUE THREAD

**Issue by Calinou** [kemitchell/oss-theory-of-operation#5]
Since CC BY-ND is not a free culture license, what about using a license like CC BY or CC BY-SA for the article content?

**Comment by kemitchell** [comment]
@Calinou: Thanks for your note.

I chose my license very carefully, and do not plan to change it.  If you or anyone else finds errors or others ways to improve the work, please feel free to share them here.  I will be very happy to improve the guide with others' help, and of course to credit and celebrate their contributions.
